using AlgorithmAnalysis
using TestItemRunner

@run_package_tests

@testitem "AlgorithmAnalysis.jl" begin
    for resultFile in getAllAutogeneratedTestResults()
        for (name, handle) in resultFile.test_cases
            @testset "$(name)" begin 
                Base.invokelatest(handle.function_pointer) 
            end
        end
    end
end