using AlgorithmAnalysis
using TestItemRunner

@run_package_tests

@testitem "AlgorithmAnalysis.jl" begin
    for resultFile in getAllAutogeneratedTestResults()
        for (name, handle) in resultFile.test_cases
            testResult = Base.invokelatest(handle.function_pointer)
            if typeof(testResult) != Bool || !testResult
                println("Test failure of test $(name) @ $(handle.function_path)");
            end
            println("running $(name)")

            @test testResult
        end
    end
end