name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: "Run CompatHelper"
        run: |
          import Pkg
          # Install CompatHelper natively in the temporary env
          Pkg.add(name="CompatHelper", uuid="aa819f21-2bde-4658-8897-bab36330d9b7", version="3")
          
          # Run it
          import CompatHelper
          CompatHelper.main()
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment and ensure this secret exists if you need SSH deploy keys:
          # COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}